<h1>DATA ANALYSIS OF NEW YORK CITI BIKERS IN PYTHON </h1>

<h2>Table of Contents</h2>

<div class="alert alert-block alert-info" style="margin-top: 20px">
<ul>
    <li><a href="https://#remove duplicates">Identify and remove duplicates</a></li>
    <li><a href="https://#identify_handle_missing_values">Identify and handle missing values</a>
        <ul>
            <li><a href="https://#identify_missing_values">Identify missing values</a></li>
            <li><a href="https://#deal_missing_values">Deal with missing values</a></li>
            <li><a href="https://#correct_data_format">Correct data format</a></li>
        </ul>
    </li>
    <li><a href="https://#data_standardization">Data standardization</a></li>
    <li><a href="https://#data_normalization">Data normalization (centering/scaling)</a></li>
    <li><a href="https://#binning">Binning</a></li>
    <li><a href="https://#indicator">Indicator variable</a></li>
</ul>

</div>

<hr>

# Import software libraries

In [20]:
import pandas as pd

# Load the dataset as a `DataFrame`

In [21]:
NY_Citi_Bikes_data=pd.read_csv('Datasets/New York Citi Bikes_Raw Data - NYCitiBikes (1).csv')

In [23]:
NY_Citi_Bikes_data

,Start Time,Stop Time,Start Station ID,Start Station Name,End Station ID,End Station Name,Bike ID,User Type,Birth Year,Age,Age Groups,Trip Duration,Trip_Duration_in_min,Month,Season,Temperature,Weekday
0,01-01-17 00:38,1-1-17 01:03,3194,McGinley Square,3271,Danforth Light Rail,24668,Subscriber,1961,60,55-64,1513,25,1,Winter,10,Sunday
1,01-01-17 01:47,01-01-17 01:58,3183,Exchange Place,3203,Hamilton Park,26167,Subscriber,1993,28,25-34,639,11,1,Winter,10,Sunday
2,01-01-17 01:47,01-01-17 01:58,3183,Exchange Place,3203,Hamilton Park,26167,Subscriber,1993,28,25-34,639,11,1,Winter,10,Sunday
3,01-01-17 01:56,01-01-17 02:00,3186,Grove St PATH,3270,Jersey & 6th St,24604,Subscriber,1970,51,45-54,258,4,1,Winter,10,Sunday
4,1-1-17 02:12,01-01-17 02:23,3270,Jersey & 6th St,3206,Hilltop,24641,Subscriber,1978,43,35-44,663,11,1,Winter,10,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,31-03-17 21:06,31-03-17 21:10,3186,Grove St PATH,3203,Hamilton Park,24608,Subscriber,1968,53,45-54,244,4,3,Spring,18,Friday
20396,31-03-17 21:13,31-3-17 21:18,3195,Sip Ave,3194,McGinley Square,29219,Subscriber,1956,65,65-74,264,4,3,Spring,18,Friday
20397,31-03-17 21:13,31-3-17 21:18,3195,Sip Ave,3194,McGinley Square,29219,Subscriber,1956,65,65-74,264,4,3,Spring,18,Friday
20398,31-03-17 21:26,31-03-17 21:30,3195,Sip Ave,3201,Dey St,29276,Subscriber,1970,51,45-54,239,4,3,Spring,18,Friday
20399,31-3-17 23:20,31-03-17 23:30,3272,Jersey & 3rd,3268,Lafayette Park,24398,Subscriber,1984,37,35-44,618,10,3,Spring,18,Friday

In [24]:
NY_Citi_Bikes_data.head(3)

,Start Time,Stop Time,Start Station ID,Start Station Name,End Station ID,End Station Name,Bike ID,User Type,Birth Year,Age,Age Groups,Trip Duration,Trip_Duration_in_min,Month,Season,Temperature,Weekday
0,01-01-17 00:38,1-1-17 01:03,3194,McGinley Square,3271,Danforth Light Rail,24668,Subscriber,1961,60,55-64,1513,25,1,Winter,10,Sunday
1,01-01-17 01:47,01-01-17 01:58,3183,Exchange Place,3203,Hamilton Park,26167,Subscriber,1993,28,25-34,639,11,1,Winter,10,Sunday
2,01-01-17 01:47,01-01-17 01:58,3183,Exchange Place,3203,Hamilton Park,26167,Subscriber,1993,28,25-34,639,11,1,Winter,10,Sunday

# Identify all duplicated data

In [26]:
duplicated_data=NY_Citi_Bikes_data[NY_Citi_Bikes_data.duplicated(keep=False)]

print('number of rows with duplicated data:', 
      duplicated_data.shape[0])

number of rows with duplicated data: 3789

In [27]:
duplicated_data

,Start Time,Stop Time,Start Station ID,Start Station Name,End Station ID,End Station Name,Bike ID,User Type,Birth Year,Age,Age Groups,Trip Duration,Trip_Duration_in_min,Month,Season,Temperature,Weekday
1,01-01-17 01:47,01-01-17 01:58,3183,Exchange Place,3203,Hamilton Park,26167,Subscriber,1993,28,25-34,639,11,1,Winter,10,Sunday
2,01-01-17 01:47,01-01-17 01:58,3183,Exchange Place,3203,Hamilton Park,26167,Subscriber,1993,28,25-34,639,11,1,Winter,10,Sunday
8,01-01-17 03:52,01-01-17 03:55,3203,Hamilton Park,3213,Van Vorst Park,24442,Subscriber,1986,35,35-44,204,3,1,Winter,10,Sunday
9,01-01-17 03:52,01-01-17 03:55,3203,Hamilton Park,3213,Van Vorst Park,24442,Subscriber,1986,35,35-44,204,3,1,Winter,10,Sunday
20,01-01-17 10:03,01-01-17 10:10,3267,Morris Canal,3273,Manila & 1st,26215,Subscriber,1957,64,55-64,424,7,1,Winter,10,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20391,31-03-17 20:46,31-03-17 20:54,3186,Grove St PATH,3203,Hamilton Park,24558,Subscriber,1967,54,45-54,467,8,3,Spring,18,Friday
20394,31-03-17 21:06,31-03-17 21:10,3186,Grove St PATH,3203,Hamilton Park,24608,Subscriber,1968,53,45-54,244,4,3,Spring,18,Friday
20395,31-03-17 21:06,31-03-17 21:10,3186,Grove St PATH,3203,Hamilton Park,24608,Subscriber,1968,53,45-54,244,4,3,Spring,18,Friday
20396,31-03-17 21:13,31-3-17 21:18,3195,Sip Ave,3194,McGinley Square,29219,Subscriber,1956,65,65-74,264,4,3,Spring,18,Friday
20397,31-03-17 21:13,31-3-17 21:18,3195,Sip Ave,3194,McGinley Square,29219,Subscriber,1956,65,65-74,264,4,3,Spring,18,Friday

# Remove the duplicated data

In [28]:
NY_Citi_Bikes_data_wt_duplicates=NY_Citi_Bikes_data[~NY_Citi_Bikes_data.duplicated()]

In [29]:
NY_Citi_Bikes_data_wt_duplicates

,Start Time,Stop Time,Start Station ID,Start Station Name,End Station ID,End Station Name,Bike ID,User Type,Birth Year,Age,Age Groups,Trip Duration,Trip_Duration_in_min,Month,Season,Temperature,Weekday
0,01-01-17 00:38,1-1-17 01:03,3194,McGinley Square,3271,Danforth Light Rail,24668,Subscriber,1961,60,55-64,1513,25,1,Winter,10,Sunday
1,01-01-17 01:47,01-01-17 01:58,3183,Exchange Place,3203,Hamilton Park,26167,Subscriber,1993,28,25-34,639,11,1,Winter,10,Sunday
3,01-01-17 01:56,01-01-17 02:00,3186,Grove St PATH,3270,Jersey & 6th St,24604,Subscriber,1970,51,45-54,258,4,1,Winter,10,Sunday
4,1-1-17 02:12,01-01-17 02:23,3270,Jersey & 6th St,3206,Hilltop,24641,Subscriber,1978,43,35-44,663,11,1,Winter,10,Sunday
5,01-01-17 02:22,1-1-17 02:31,3212,Christ Hospital,3225,Baldwin at Montgomery,24520,Subscriber,1987,34,25-34,535,9,1,Winter,10,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20393,31-3-17 21:03,31-3-17 21:12,3278,Monmouth and 6th,3278,Monmouth and 6th,26221,Subscriber,1958,63,55-64,577,10,3,Spring,18,Friday
20394,31-03-17 21:06,31-03-17 21:10,3186,Grove St PATH,3203,Hamilton Park,24608,Subscriber,1968,53,45-54,244,4,3,Spring,18,Friday
20396,31-03-17 21:13,31-3-17 21:18,3195,Sip Ave,3194,McGinley Square,29219,Subscriber,1956,65,65-74,264,4,3,Spring,18,Friday
20398,31-03-17 21:26,31-03-17 21:30,3195,Sip Ave,3201,Dey St,29276,Subscriber,1970,51,45-54,239,4,3,Spring,18,Friday
20399,31-3-17 23:20,31-03-17 23:30,3272,Jersey & 3rd,3268,Lafayette Park,24398,Subscriber,1984,37,35-44,618,10,3,Spring,18,Friday